execution_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "FAILED"]
auth_users: [['user_1', 'pass_1'], ['user_2', 'pass_2'], ['user_3', 'pass_3'],['user_4', 'pass_4'],['user_5', 'pass_5']]
sample_codes: ["50 * 15", "32 + 41", "42.66 - 5.33", "42 % 3", "1000 / 2000"]
invalid_code: ["7864 + invalid_code", "print(test)"]
special_characters_codes: ["code with @ symbol", "code with # symbols." ]
test_file_name: test_code.txt